[build]
    functions = "api"
    command = "bun run build"

[functions]
   node_bundler = "esbuild"
   external_node_modules = ["@sparticuz/chromium"]

# this is actually a Rewrite
# totally optional, but makes up for
# a much better UX
[[redirects]]
from = "/"
to = "/.netlify/functions/index"
status = 200